Release v1.2.0
fw4-bvba/skarabee-weblink pull request #6
Opened 2023-01-17 09:39 UTC by Fyrts

2023-01-26 12:24 UTC, DeKerpelLaurent requested changes

2023-01-26 12:24 UTC, DeKerpelLaurent commented on src/ApiAdapter/ApiAdapter.php
>          return is_object($response) ? $response : null;
condition always false

2023-01-26 12:24 UTC, DeKerpelLaurent commented on src/Response/ProjectSummaryResponse.php
> +        ], $arrays));
array_merge 1 array ?

2023-01-26 12:24 UTC, DeKerpelLaurent commented on src/Response/Response.php
>              $data = (reset($data) ?? false) ?: [];
this will break at some point

2023-01-26 12:24 UTC, DeKerpelLaurent commented on src/Response/ResponseObject.php
> +                    $value = (array)$data->$array;
sure this works ?

2023-01-27 09:13 UTC, Fyrts commented on src/Response/ProjectSummaryResponse.php
> +        ], $arrays));
array_merge of 2 associative arrays

2023-01-27 09:14 UTC, Fyrts commented on src/ApiAdapter/ApiAdapter.php
>          return is_object($response) ? $response : null;
Depends on the content of $response

2023-01-30 12:40 UTC, DeKerpelLaurent approved these changes

2023-01-30 12:41 UTC, merged